name: deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:iron-slim
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: mayaal-design-build
        path: dist
        if-no-files-found: error
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: mayaal-design-build
        path: dist
    - name: SSH setup
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CICD_SSH_HOST_FINGERPRINT }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.CICD_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod -R 700 ~/.ssh
    - name: Rsync deployment
      env:
        REMOTE_DIRECTORY: /var/www/mayaal-design
      run: |
        cd dist
        rsync \
          -avz \
          -e ssh \
          --delete \
          . \
          ${{ secrets.CICD_SSH_USER }}@${{ secrets.CICD_SSH_HOST}}:${{ env.REMOTE_DIRECTORY }}
