name: deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SSH setup
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CICD_SSH_HOST_FINGERPRINT }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.CICD_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod -R 700 ~/.ssh
    - name: Rsync deployment
      env:
        REMOTE_DIRECTORY: /var/www/mayaal-design
      run: |
        rsync \
          -avz \
          --exclude '.git' \
          --exclude '.github' \
          -e ssh \
          --delete . \
          ${{ secrets.CICD_SSH_USER }}@${{ secrets.CICD_SSH_HOST}}:${{ env.REMOTE_DIRECTORY }}